import { useFrame } from "@react-three/fiber";
import { useMemo, useRef } from "react";
import * as THREE from "three";
import { EnergyField, FresnelShell } from "../shared/materials";
import { P } from "../shared/palette";
import { Particles } from "../shared/Particles";
import { easeOutBack, easeOutExpo } from "../shared/easing";
import { VolumetricNumber } from "../shared/VolumetricNumber";
import type { Design, SceneProps } from "../shared/types";

/**
 * WIN 05 — GEODE
 *
 * A sealed stone cracks along six seams and hinges open, and what is inside is light.
 *
 * The shell halves are generated by taking one lathed silhouette and splitting it into six wedges
 * that rotate away from a shared axis, so the fracture lines are real geometry boundaries rather
 * than a texture. Because each wedge keeps its own inner face, the opened stone shows a rough
 * interior — which is what distinguishes a geode from a hollow ball.
 */

const WEDGES = 6;

function useShellGeometry() {
  return useMemo(() => {
    const profile: THREE.Vector2[] = [];
    for (let i = 0; i <= 14; i++) {
      const t = i / 14;
      const a = t * Math.PI;
      // An irregular radius — a rock, not a sphere.
      const r = Math.sin(a) * (1.72 + Math.sin(a * 5.2) * 0.12 + Math.cos(a * 3.1) * 0.09);
      profile.push(new THREE.Vector2(Math.max(r, 0.001), Math.cos(a) * 1.85));
    }
    const geo = new THREE.LatheGeometry(profile, 4, 0, (Math.PI * 2) / WEDGES);
    geo.computeVertexNormals();
    return geo;
  }, []);
}

function Shell({ open }: { open: number }) {
  const shellGeo = useShellGeometry();
  const wedges = useRef<THREE.Group[]>([]);

  const outer = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: P.abyss,
        metalness: 0.4,
        roughness: 0.85,
        flatShading: true,
        side: THREE.DoubleSide,
      }),
    [],
  );
  // The interior is where the value break lives: rough dark outside, charged violet inside.
  const inner = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: P.violet,
        emissive: P.electric,
        emissiveIntensity: 0.9,
        metalness: 0.75,
        roughness: 0.25,
        flatShading: true,
        side: THREE.BackSide,
      }),
    [],
  );

  useFrame((state) => {
    const t = state.clock.elapsedTime;
    wedges.current.forEach((g, i) => {
      if (!g) return;
      const a = (i / WEDGES) * Math.PI * 2;
      // Each wedge hinges outward and drifts along its own radial, with a slow tumble once free.
      g.rotation.y = a;
      g.rotation.z = open * 0.55 * (i % 2 ? 1 : -1);
      g.position.set(Math.cos(a) * open * 1.5, Math.sin(t * 0.5 + i) * open * 0.28, Math.sin(a) * open * 1.5);
      g.scale.setScalar(1 - open * 0.12);
    });
  });

  return (
    <group>
      {Array.from({ length: WEDGES }, (_, i) => (
        <group key={i} ref={(g) => { if (g) wedges.current[i] = g; }}>
          <mesh geometry={shellGeo} material={outer} />
          <mesh geometry={shellGeo} material={inner} scale={0.97} />
        </group>
      ))}
    </group>
  );
}

/** Crystal teeth lining the cavity, revealed as the shell parts. */
function Teeth({ open }: { open: number }) {
  const geo = useMemo(() => new THREE.ConeGeometry(0.11, 0.55, 4), []);
  const material = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: P.mist,
        emissive: P.lavender,
        emissiveIntensity: 1.1,
        metalness: 0.5,
        roughness: 0.15,
        flatShading: true,
        transparent: true,
      }),
    [],
  );

  const spikes = useMemo(
    () =>
      Array.from({ length: 26 }, () => {
        const theta = Math.random() * Math.PI * 2;
        const phi = Math.acos(2 * Math.random() - 1);
        return new THREE.Vector3(
          Math.sin(phi) * Math.cos(theta),
          Math.cos(phi),
          Math.sin(phi) * Math.sin(theta),
        );
      }),
    [],
  );

  useFrame(() => {
    material.opacity = open;
  });

  return (
    <group>
      {spikes.map((dir, i) => {
        const pos = dir.clone().multiplyScalar(1.42);
        const q = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir.clone().negate());
        return (
          <mesh
            key={i}
            geometry={geo}
            material={material}
            position={pos}
            quaternion={q}
            scale={0.6 + ((i * 37) % 10) / 14}
          />
        );
      })}
    </group>
  );
}

function Scene({ value, progress }: SceneProps) {
  const open = easeOutExpo(Math.min(progress * 1.8, 1));
  const reveal = easeOutBack(THREE.MathUtils.clamp((progress - 0.26) / 0.42, 0, 1), 1.6);
  const core = useRef<THREE.Group>(null);
  const flash = useRef<THREE.PointLight>(null);

  useFrame((state) => {
    const t = state.clock.elapsedTime;
    if (core.current) core.current.rotation.y = t * 0.13;
    if (flash.current) flash.current.intensity = 10 + open * 44;
  });

  return (
    <>
      <ambientLight intensity={0.3} color={P.mist} />
      <directionalLight position={[5, 6, 5]} intensity={1.9} color={P.highlight} />
      <pointLight ref={flash} position={[0, 0, 0]} intensity={10} color={P.lavender} distance={11} />
      <pointLight position={[-5, -3, 3]} intensity={26} color={P.electric} distance={18} />

      <group ref={core}>
        <Shell open={open} />
        <Teeth open={open} />

        <EnergyField colorA={P.electric} colorB={P.ember} speed={0.9} density={2.8} intensity={0.6 + open * 1.1}>
          <sphereGeometry args={[1.25, 40, 30]} />
        </EnergyField>

        <group scale={reveal}>
          <VolumetricNumber
            key={String(value)}
            value={value}
            size={1.85}
            depth={0.4}
            face={P.highlight}
            body={P.violet}
            edge={P.ember}
            intensity={1.25}
          />
        </group>

        <FresnelShell color={P.lavender} power={2.8} intensity={0.5 + open * 0.9}>
          <sphereGeometry args={[2.6, 32, 24]} />
        </FresnelShell>
      </group>

      <Particles motion="updraft" count={220} color={P.lavender} spread={4.8} size={0.045} speed={1.2} />
      <Particles motion="drift" count={120} color={P.mist} spread={7.5} size={0.028} opacity={0.4} />
    </>
  );
}

export const Victory05: Design = {
  id: "victory-05",
  name: "Geode",
  nameAr: "الجيود",
  descriptionAr: "حجر مقفول بينشق على ست قطع ويفتح على جوف مليان بلورات وضوء.",
  Scene,
  camera: { position: [0, 0, 7.8], fov: 45 },
  effects: { bloom: 0.9, bloomThreshold: 0.48, chromatic: 0.0009, vignette: 0.55 },
  parallax: 0.5,
};
