export interface CapitalQuestion {
  /** ISO 3166-1 alpha-2 country code — reuses Flags' own `public/flags/<code>.svg` assets, no
   *  separate image set needed. */
  code: string;
  /** Shown in the question itself ("عاصمة <country> ايه؟"). */
  country: string;
  /** The capital's answers[0] is also what `CapitalsState.capitalName` reveals. */
  answers: string[];
}

/**
 * The built-in capitals bank — same 195-country roster as Flags (every UN member plus Vatican
 * City and Palestine), kept as its own standalone dataset rather than importing from
 * `flagsQuestions.ts` (each game's content is self-contained, matching the `triviaQuestions.ts`
 * precedent). A few notes on picks that aren't clear-cut:
 * - Where a country has multiple widely-cited capitals (seat of government vs. constitutional/
 *   judicial capital — South Africa, Bolivia, Sri Lanka's official name, ...), `answers[0]` is
 *   whichever city is most commonly known as "the capital" in general knowledge, with the
 *   official/alternate one listed second where it's still commonly cited.
 * - Israel's capital is given as Tel Aviv, matching standard Arabic-media convention rather than
 *   Israel's own claim of Jerusalem; Palestine's is given as Jerusalem, the Arabic-recognized
 *   capital, with Ramallah (the PA's actual administrative seat) as a second accepted answer.
 */
export const CAPITALS_QUESTIONS: CapitalQuestion[] = [
  // --- Africa (54) ---
  { code: "dz", country: "الجزائر", answers: ["الجزائر"] },
  { code: "ao", country: "أنغولا", answers: ["لواندا"] },
  { code: "bj", country: "بنين", answers: ["بورتو نوفو", "كوتونو"] },
  { code: "bw", country: "بوتسوانا", answers: ["غابورون"] },
  { code: "bf", country: "بوركينا فاسو", answers: ["واغادوغو"] },
  { code: "bi", country: "بوروندي", answers: ["غيتيغا", "بوجومبورا"] },
  { code: "cv", country: "الرأس الأخضر", answers: ["برايا"] },
  { code: "cm", country: "الكاميرون", answers: ["ياوندي"] },
  { code: "cf", country: "أفريقيا الوسطى", answers: ["بانغي"] },
  { code: "td", country: "تشاد", answers: ["نجامينا"] },
  { code: "km", country: "جزر القمر", answers: ["موروني"] },
  { code: "cg", country: "الكونغو", answers: ["برازافيل"] },
  { code: "cd", country: "الكونغو الديمقراطية", answers: ["كينشاسا"] },
  { code: "dj", country: "جيبوتي", answers: ["جيبوتي"] },
  { code: "eg", country: "مصر", answers: ["القاهرة"] },
  { code: "gq", country: "غينيا الاستوائية", answers: ["مالابو"] },
  { code: "er", country: "إريتريا", answers: ["أسمرة"] },
  { code: "sz", country: "إسواتيني", answers: ["مبابان"] },
  { code: "et", country: "إثيوبيا", answers: ["أديس أبابا"] },
  { code: "ga", country: "الغابون", answers: ["ليبرفيل"] },
  { code: "gm", country: "غامبيا", answers: ["بانجول"] },
  { code: "gh", country: "غانا", answers: ["أكرا"] },
  { code: "gn", country: "غينيا", answers: ["كوناكري"] },
  { code: "gw", country: "غينيا بيساو", answers: ["بيساو"] },
  { code: "ci", country: "ساحل العاج", answers: ["ياموسوكرو", "أبيدجان"] },
  { code: "ke", country: "كينيا", answers: ["نيروبي"] },
  { code: "ls", country: "ليسوتو", answers: ["ماسيرو"] },
  { code: "lr", country: "ليبيريا", answers: ["مونروفيا"] },
  { code: "ly", country: "ليبيا", answers: ["طرابلس"] },
  { code: "mg", country: "مدغشقر", answers: ["أنتاناناريفو"] },
  { code: "mw", country: "مالاوي", answers: ["ليلونجوي"] },
  { code: "ml", country: "مالي", answers: ["باماكو"] },
  { code: "mr", country: "موريتانيا", answers: ["نواكشوط"] },
  { code: "mu", country: "موريشيوس", answers: ["بورت لويس"] },
  { code: "ma", country: "المغرب", answers: ["الرباط"] },
  { code: "mz", country: "موزمبيق", answers: ["مابوتو"] },
  { code: "na", country: "ناميبيا", answers: ["ويندهوك"] },
  { code: "ne", country: "النيجر", answers: ["نيامي"] },
  { code: "ng", country: "نيجيريا", answers: ["أبوجا"] },
  { code: "rw", country: "رواندا", answers: ["كيغالي"] },
  { code: "st", country: "ساو تومي وبرينسيبي", answers: ["ساو تومي"] },
  { code: "sn", country: "السنغال", answers: ["داكار"] },
  { code: "sc", country: "سيشل", answers: ["فيكتوريا"] },
  { code: "sl", country: "سيراليون", answers: ["فريتاون"] },
  { code: "so", country: "الصومال", answers: ["مقديشو"] },
  { code: "za", country: "جنوب أفريقيا", answers: ["بريتوريا", "كيب تاون"] },
  { code: "ss", country: "جنوب السودان", answers: ["جوبا"] },
  { code: "sd", country: "السودان", answers: ["الخرطوم"] },
  { code: "tz", country: "تنزانيا", answers: ["دودوما", "دار السلام"] },
  { code: "tg", country: "توغو", answers: ["لومي"] },
  { code: "tn", country: "تونس", answers: ["تونس"] },
  { code: "ug", country: "أوغندا", answers: ["كمبالا"] },
  { code: "zm", country: "زامبيا", answers: ["لوساكا"] },
  { code: "zw", country: "زيمبابوي", answers: ["هراري"] },

  // --- Asia (46, incl. Palestine) ---
  { code: "af", country: "أفغانستان", answers: ["كابول"] },
  { code: "am", country: "أرمينيا", answers: ["يريفان"] },
  { code: "az", country: "أذربيجان", answers: ["باكو"] },
  { code: "bh", country: "البحرين", answers: ["المنامة"] },
  { code: "bd", country: "بنغلاديش", answers: ["دكا"] },
  { code: "bt", country: "بوتان", answers: ["تيمفو"] },
  { code: "bn", country: "بروناي", answers: ["بندر سري بكاوان"] },
  { code: "kh", country: "كمبوديا", answers: ["بنوم بنه"] },
  { code: "cn", country: "الصين", answers: ["بكين"] },
  { code: "ge", country: "جورجيا", answers: ["تبليسي"] },
  { code: "in", country: "الهند", answers: ["نيودلهي", "دلهي"] },
  { code: "id", country: "إندونيسيا", answers: ["جاكرتا"] },
  { code: "ir", country: "إيران", answers: ["طهران"] },
  { code: "iq", country: "العراق", answers: ["بغداد"] },
  { code: "il", country: "إسرائيل", answers: ["تل أبيب"] },
  { code: "jp", country: "اليابان", answers: ["طوكيو"] },
  { code: "jo", country: "الأردن", answers: ["عمان"] },
  { code: "kz", country: "كازاخستان", answers: ["أستانا", "نور سلطان"] },
  { code: "kw", country: "الكويت", answers: ["الكويت"] },
  { code: "kg", country: "قيرغيزستان", answers: ["بيشكيك"] },
  { code: "la", country: "لاوس", answers: ["فيينتيان"] },
  { code: "lb", country: "لبنان", answers: ["بيروت"] },
  { code: "my", country: "ماليزيا", answers: ["كوالالمبور"] },
  { code: "mv", country: "المالديف", answers: ["ماليه"] },
  { code: "mn", country: "منغوليا", answers: ["أولان باتور"] },
  { code: "mm", country: "ميانمار", answers: ["نايبيداو", "يانغون"] },
  { code: "np", country: "نيبال", answers: ["كاتماندو"] },
  { code: "kp", country: "كوريا الشمالية", answers: ["بيونغ يانغ"] },
  { code: "om", country: "عمان", answers: ["مسقط"] },
  { code: "pk", country: "باكستان", answers: ["إسلام آباد"] },
  { code: "ps", country: "فلسطين", answers: ["القدس", "رام الله"] },
  { code: "ph", country: "الفلبين", answers: ["مانيلا"] },
  { code: "qa", country: "قطر", answers: ["الدوحة"] },
  { code: "sa", country: "السعودية", answers: ["الرياض"] },
  { code: "sg", country: "سنغافورة", answers: ["سنغافورة"] },
  { code: "kr", country: "كوريا الجنوبية", answers: ["سيول"] },
  { code: "lk", country: "سريلانكا", answers: ["كولومبو"] },
  { code: "sy", country: "سوريا", answers: ["دمشق"] },
  { code: "tj", country: "طاجيكستان", answers: ["دوشنبي"] },
  { code: "th", country: "تايلاند", answers: ["بانكوك"] },
  { code: "tl", country: "تيمور الشرقية", answers: ["ديلي"] },
  { code: "tr", country: "تركيا", answers: ["أنقرة"] },
  { code: "tm", country: "تركمانستان", answers: ["عشق آباد"] },
  { code: "ae", country: "الإمارات", answers: ["أبوظبي"] },
  { code: "uz", country: "أوزبكستان", answers: ["طشقند"] },
  { code: "vn", country: "فيتنام", answers: ["هانوي"] },
  { code: "ye", country: "اليمن", answers: ["صنعاء"] },

  // --- Europe (45, incl. Vatican) ---
  { code: "al", country: "ألبانيا", answers: ["تيرانا"] },
  { code: "ad", country: "أندورا", answers: ["أندورا لا فيلا"] },
  { code: "at", country: "النمسا", answers: ["فيينا"] },
  { code: "by", country: "بيلاروسيا", answers: ["مينسك"] },
  { code: "be", country: "بلجيكا", answers: ["بروكسل"] },
  { code: "ba", country: "البوسنة والهرسك", answers: ["سراييفو"] },
  { code: "bg", country: "بلغاريا", answers: ["صوفيا"] },
  { code: "hr", country: "كرواتيا", answers: ["زغرب"] },
  { code: "cy", country: "قبرص", answers: ["نيقوسيا"] },
  { code: "cz", country: "التشيك", answers: ["براغ"] },
  { code: "dk", country: "الدنمارك", answers: ["كوبنهاغن"] },
  { code: "ee", country: "إستونيا", answers: ["تالين"] },
  { code: "fi", country: "فنلندا", answers: ["هلسنكي"] },
  { code: "fr", country: "فرنسا", answers: ["باريس"] },
  { code: "de", country: "ألمانيا", answers: ["برلين"] },
  { code: "gr", country: "اليونان", answers: ["أثينا"] },
  { code: "hu", country: "المجر", answers: ["بودابست"] },
  { code: "is", country: "آيسلندا", answers: ["ريكيافيك"] },
  { code: "ie", country: "أيرلندا", answers: ["دبلن"] },
  { code: "it", country: "إيطاليا", answers: ["روما"] },
  { code: "lv", country: "لاتفيا", answers: ["ريغا"] },
  { code: "li", country: "ليختنشتاين", answers: ["فادوز"] },
  { code: "lt", country: "ليتوانيا", answers: ["فيلنيوس"] },
  { code: "lu", country: "لوكسمبورغ", answers: ["لوكسمبورغ"] },
  { code: "mt", country: "مالطا", answers: ["فاليتا"] },
  { code: "md", country: "مولدوفا", answers: ["كيشيناو"] },
  { code: "mc", country: "موناكو", answers: ["موناكو"] },
  { code: "me", country: "الجبل الأسود", answers: ["بودغوريتسا"] },
  { code: "nl", country: "هولندا", answers: ["أمستردام", "لاهاي"] },
  { code: "mk", country: "مقدونيا الشمالية", answers: ["سكوبيه"] },
  { code: "no", country: "النرويج", answers: ["أوسلو"] },
  { code: "pl", country: "بولندا", answers: ["وارسو"] },
  { code: "pt", country: "البرتغال", answers: ["لشبونة"] },
  { code: "ro", country: "رومانيا", answers: ["بوخارست"] },
  { code: "ru", country: "روسيا", answers: ["موسكو"] },
  { code: "sm", country: "سان مارينو", answers: ["سان مارينو"] },
  { code: "rs", country: "صربيا", answers: ["بلغراد"] },
  { code: "sk", country: "سلوفاكيا", answers: ["براتيسلافا"] },
  { code: "si", country: "سلوفينيا", answers: ["ليوبليانا"] },
  { code: "es", country: "إسبانيا", answers: ["مدريد"] },
  { code: "se", country: "السويد", answers: ["ستوكهولم"] },
  { code: "ch", country: "سويسرا", answers: ["برن"] },
  { code: "ua", country: "أوكرانيا", answers: ["كييف"] },
  { code: "gb", country: "بريطانيا", answers: ["لندن"] },
  { code: "va", country: "الفاتيكان", answers: ["الفاتيكان"] },

  // --- North America (23) ---
  { code: "ag", country: "أنتيغوا وباربودا", answers: ["سانت جونز"] },
  { code: "bs", country: "الباهاما", answers: ["ناسو"] },
  { code: "bb", country: "باربادوس", answers: ["بريدجتاون"] },
  { code: "bz", country: "بليز", answers: ["بلموبان"] },
  { code: "ca", country: "كندا", answers: ["أوتاوا"] },
  { code: "cr", country: "كوستاريكا", answers: ["سان خوسيه"] },
  { code: "cu", country: "كوبا", answers: ["هافانا"] },
  { code: "dm", country: "دومينيكا", answers: ["روزو"] },
  { code: "do", country: "جمهورية الدومينيكان", answers: ["سانتو دومينغو"] },
  { code: "sv", country: "السلفادور", answers: ["سان سلفادور"] },
  { code: "gd", country: "غرينادا", answers: ["سانت جورج"] },
  { code: "gt", country: "غواتيمالا", answers: ["مدينة غواتيمالا", "غواتيمالا سيتي"] },
  { code: "ht", country: "هايتي", answers: ["بورت أو برنس"] },
  { code: "hn", country: "هندوراس", answers: ["تيغوسيغالبا"] },
  { code: "jm", country: "جامايكا", answers: ["كينغستون"] },
  { code: "mx", country: "المكسيك", answers: ["مكسيكو سيتي", "مدينة مكسيكو"] },
  { code: "ni", country: "نيكاراغوا", answers: ["ماناغوا"] },
  { code: "pa", country: "بنما", answers: ["بنما"] },
  { code: "kn", country: "سانت كيتس ونيفيس", answers: ["باستير"] },
  { code: "lc", country: "سانت لوسيا", answers: ["كاستريس"] },
  { code: "vc", country: "سانت فينسنت والغرينادين", answers: ["كينغستاون"] },
  { code: "tt", country: "ترينيداد وتوباغو", answers: ["بورت أوف سبين"] },
  { code: "us", country: "أمريكا", answers: ["واشنطن"] },

  // --- South America (12) ---
  { code: "ar", country: "الأرجنتين", answers: ["بوينس آيرس"] },
  { code: "bo", country: "بوليفيا", answers: ["لاباز", "سوكري"] },
  { code: "br", country: "البرازيل", answers: ["برازيليا"] },
  { code: "cl", country: "تشيلي", answers: ["سانتياغو"] },
  { code: "co", country: "كولومبيا", answers: ["بوغوتا"] },
  { code: "ec", country: "الإكوادور", answers: ["كيتو"] },
  { code: "gy", country: "غيانا", answers: ["جورجتاون"] },
  { code: "py", country: "باراغواي", answers: ["أسونسيون"] },
  { code: "pe", country: "بيرو", answers: ["ليما"] },
  { code: "sr", country: "سورينام", answers: ["باراماريبو"] },
  { code: "uy", country: "أوروغواي", answers: ["مونتيفيديو"] },
  { code: "ve", country: "فنزويلا", answers: ["كاراكاس"] },

  // --- Oceania (14) ---
  { code: "au", country: "أستراليا", answers: ["كانبيرا"] },
  { code: "fj", country: "فيجي", answers: ["سوفا"] },
  { code: "ki", country: "كيريباتي", answers: ["تاراوا"] },
  { code: "mh", country: "جزر مارشال", answers: ["ماجورو"] },
  { code: "fm", country: "ميكرونيزيا", answers: ["باليكير"] },
  { code: "nr", country: "ناورو", answers: ["يارين"] },
  { code: "nz", country: "نيوزيلندا", answers: ["ويلينغتون"] },
  { code: "pw", country: "بالاو", answers: ["نجيرولمود"] },
  { code: "pg", country: "بابوا غينيا الجديدة", answers: ["بورت مورسبي"] },
  { code: "ws", country: "ساموا", answers: ["آبيا"] },
  { code: "sb", country: "جزر سليمان", answers: ["هونيارا"] },
  { code: "to", country: "تونغا", answers: ["نوكوعالوفا"] },
  { code: "tv", country: "توفالو", answers: ["فونافوتي"] },
  { code: "vu", country: "فانواتو", answers: ["بورت فيلا"] },
];
