export interface FlagQuestion {
  /** ISO 3166-1 alpha-2 country code, lowercase — matches the downloaded SVG filenames at
   *  `public/flags/<code>.svg` on both frontends, so the wire only ever carries a code, never an
   *  emoji (Windows/Chrome and OBS's Chromium Embedded Framework routinely fail to render
   *  Unicode flag emoji, silently falling back to the two-letter code as plain text — real flag
   *  artwork sidesteps that). */
  code: string;
  answers: string[];
}

/**
 * The built-in flag bank — every UN member state plus Vatican City and Palestine (~195 flags),
 * organized by region below purely for editing sanity; the engine just deals from the flat array
 * shuffled. `answers[0]` is also what `FlagsState.countryName` reveals, so keep it the most
 * natural/common Arabic name. Alternate spellings only need listing when they're genuinely
 * different words (e.g. "بريطانيا" vs "المملكة المتحدة") — hamza/teh-marbuta variants are already
 * unified by `normalizeAnswer()`, so "أمريكا" already matches "امريكا" without a second entry.
 */
export const FLAGS_QUESTIONS: FlagQuestion[] = [
  // --- Africa (54) ---
  { code: "dz", answers: ["الجزائر"] },
  { code: "ao", answers: ["أنغولا"] },
  { code: "bj", answers: ["بنين"] },
  { code: "bw", answers: ["بوتسوانا"] },
  { code: "bf", answers: ["بوركينا فاسو"] },
  { code: "bi", answers: ["بوروندي"] },
  { code: "cv", answers: ["الرأس الأخضر"] },
  { code: "cm", answers: ["الكاميرون"] },
  { code: "cf", answers: ["أفريقيا الوسطى", "جمهورية أفريقيا الوسطى"] },
  { code: "td", answers: ["تشاد"] },
  { code: "km", answers: ["جزر القمر", "القمر"] },
  { code: "cg", answers: ["الكونغو", "جمهورية الكونغو"] },
  { code: "cd", answers: ["الكونغو الديمقراطية", "الكونغو الديموقراطية"] },
  { code: "dj", answers: ["جيبوتي"] },
  { code: "eg", answers: ["مصر"] },
  { code: "gq", answers: ["غينيا الاستوائية"] },
  { code: "er", answers: ["إريتريا"] },
  { code: "sz", answers: ["إسواتيني", "سوازيلاند"] },
  { code: "et", answers: ["إثيوبيا"] },
  { code: "ga", answers: ["الغابون"] },
  { code: "gm", answers: ["غامبيا"] },
  { code: "gh", answers: ["غانا"] },
  { code: "gn", answers: ["غينيا"] },
  { code: "gw", answers: ["غينيا بيساو"] },
  { code: "ci", answers: ["ساحل العاج"] },
  { code: "ke", answers: ["كينيا"] },
  { code: "ls", answers: ["ليسوتو"] },
  { code: "lr", answers: ["ليبيريا"] },
  { code: "ly", answers: ["ليبيا"] },
  { code: "mg", answers: ["مدغشقر"] },
  { code: "mw", answers: ["مالاوي"] },
  { code: "ml", answers: ["مالي"] },
  { code: "mr", answers: ["موريتانيا"] },
  { code: "mu", answers: ["موريشيوس"] },
  { code: "ma", answers: ["المغرب"] },
  { code: "mz", answers: ["موزمبيق"] },
  { code: "na", answers: ["ناميبيا"] },
  { code: "ne", answers: ["النيجر"] },
  { code: "ng", answers: ["نيجيريا"] },
  { code: "rw", answers: ["رواندا"] },
  { code: "st", answers: ["ساو تومي وبرينسيبي"] },
  { code: "sn", answers: ["السنغال"] },
  { code: "sc", answers: ["سيشل"] },
  { code: "sl", answers: ["سيراليون"] },
  { code: "so", answers: ["الصومال"] },
  { code: "za", answers: ["جنوب أفريقيا"] },
  { code: "ss", answers: ["جنوب السودان"] },
  { code: "sd", answers: ["السودان"] },
  { code: "tz", answers: ["تنزانيا"] },
  { code: "tg", answers: ["توغو"] },
  { code: "tn", answers: ["تونس"] },
  { code: "ug", answers: ["أوغندا"] },
  { code: "zm", answers: ["زامبيا"] },
  { code: "zw", answers: ["زيمبابوي"] },

  // --- Asia (46, incl. Palestine) ---
  { code: "af", answers: ["أفغانستان"] },
  { code: "am", answers: ["أرمينيا"] },
  { code: "az", answers: ["أذربيجان"] },
  { code: "bh", answers: ["البحرين"] },
  { code: "bd", answers: ["بنغلاديش", "بنجلاديش"] },
  { code: "bt", answers: ["بوتان"] },
  { code: "bn", answers: ["بروناي"] },
  { code: "kh", answers: ["كمبوديا"] },
  { code: "cn", answers: ["الصين"] },
  { code: "ge", answers: ["جورجيا"] },
  { code: "in", answers: ["الهند"] },
  { code: "id", answers: ["إندونيسيا"] },
  { code: "iq", answers: ["العراق"] },
  { code: "jp", answers: ["اليابان"] },
  { code: "jo", answers: ["الأردن"] },
  { code: "kz", answers: ["كازاخستان"] },
  { code: "kw", answers: ["الكويت"] },
  { code: "kg", answers: ["قيرغيزستان"] },
  { code: "la", answers: ["لاوس"] },
  { code: "lb", answers: ["لبنان"] },
  { code: "my", answers: ["ماليزيا"] },
  { code: "mv", answers: ["المالديف"] },
  { code: "mn", answers: ["منغوليا"] },
  { code: "mm", answers: ["ميانمار", "بورما"] },
  { code: "np", answers: ["نيبال"] },
  { code: "kp", answers: ["كوريا الشمالية"] },
  { code: "om", answers: ["عمان", "عُمان"] },
  { code: "pk", answers: ["باكستان"] },
  { code: "ps", answers: ["فلسطين"] },
  { code: "ph", answers: ["الفلبين"] },
  { code: "qa", answers: ["قطر"] },
  { code: "sa", answers: ["السعودية", "المملكة العربية السعودية"] },
  { code: "sg", answers: ["سنغافورة"] },
  { code: "kr", answers: ["كوريا الجنوبية", "كوريا"] },
  { code: "lk", answers: ["سريلانكا"] },
  { code: "sy", answers: ["سوريا", "سورية"] },
  { code: "tj", answers: ["طاجيكستان"] },
  { code: "th", answers: ["تايلاند"] },
  { code: "tl", answers: ["تيمور الشرقية"] },
  { code: "tr", answers: ["تركيا"] },
  { code: "tm", answers: ["تركمانستان"] },
  { code: "ae", answers: ["الإمارات", "دولة الإمارات"] },
  { code: "uz", answers: ["أوزبكستان"] },
  { code: "vn", answers: ["فيتنام"] },
  { code: "ye", answers: ["اليمن"] },

  // --- Europe (45, incl. Vatican) ---
  { code: "al", answers: ["ألبانيا"] },
  { code: "ad", answers: ["أندورا"] },
  { code: "at", answers: ["النمسا"] },
  { code: "by", answers: ["بيلاروسيا"] },
  { code: "be", answers: ["بلجيكا"] },
  { code: "ba", answers: ["البوسنة والهرسك", "البوسنة"] },
  { code: "bg", answers: ["بلغاريا"] },
  { code: "hr", answers: ["كرواتيا"] },
  { code: "cy", answers: ["قبرص"] },
  { code: "cz", answers: ["التشيك"] },
  { code: "dk", answers: ["الدنمارك"] },
  { code: "ee", answers: ["إستونيا"] },
  { code: "fi", answers: ["فنلندا"] },
  { code: "fr", answers: ["فرنسا"] },
  { code: "de", answers: ["ألمانيا"] },
  { code: "gr", answers: ["اليونان"] },
  { code: "hu", answers: ["المجر", "هنغاريا"] },
  { code: "is", answers: ["آيسلندا"] },
  { code: "ie", answers: ["أيرلندا"] },
  { code: "it", answers: ["إيطاليا"] },
  { code: "lv", answers: ["لاتفيا"] },
  { code: "li", answers: ["ليختنشتاين"] },
  { code: "lt", answers: ["ليتوانيا"] },
  { code: "lu", answers: ["لوكسمبورغ"] },
  { code: "mt", answers: ["مالطا"] },
  { code: "md", answers: ["مولدوفا"] },
  { code: "mc", answers: ["موناكو"] },
  { code: "me", answers: ["الجبل الأسود"] },
  { code: "nl", answers: ["هولندا"] },
  { code: "mk", answers: ["مقدونيا الشمالية", "مقدونيا"] },
  { code: "no", answers: ["النرويج"] },
  { code: "pl", answers: ["بولندا"] },
  { code: "pt", answers: ["البرتغال"] },
  { code: "ro", answers: ["رومانيا"] },
  { code: "ru", answers: ["روسيا"] },
  { code: "sm", answers: ["سان مارينو"] },
  { code: "rs", answers: ["صربيا"] },
  { code: "sk", answers: ["سلوفاكيا"] },
  { code: "si", answers: ["سلوفينيا"] },
  { code: "es", answers: ["إسبانيا"] },
  { code: "se", answers: ["السويد"] },
  { code: "ch", answers: ["سويسرا"] },
  { code: "ua", answers: ["أوكرانيا"] },
  { code: "gb", answers: ["بريطانيا", "المملكة المتحدة", "إنجلترا"] },
  { code: "va", answers: ["الفاتيكان"] },

  // --- North America (23) ---
  { code: "ag", answers: ["أنتيغوا وباربودا"] },
  { code: "bs", answers: ["الباهاما", "باهاماس"] },
  { code: "bb", answers: ["باربادوس"] },
  { code: "bz", answers: ["بليز"] },
  { code: "ca", answers: ["كندا"] },
  { code: "cr", answers: ["كوستاريكا"] },
  { code: "cu", answers: ["كوبا"] },
  { code: "dm", answers: ["دومينيكا"] },
  { code: "do", answers: ["جمهورية الدومينيكان"] },
  { code: "sv", answers: ["السلفادور"] },
  { code: "gd", answers: ["غرينادا"] },
  { code: "gt", answers: ["غواتيمالا"] },
  { code: "ht", answers: ["هايتي"] },
  { code: "hn", answers: ["هندوراس"] },
  { code: "jm", answers: ["جامايكا"] },
  { code: "mx", answers: ["المكسيك"] },
  { code: "ni", answers: ["نيكاراغوا"] },
  { code: "pa", answers: ["بنما"] },
  { code: "kn", answers: ["سانت كيتس ونيفيس"] },
  { code: "lc", answers: ["سانت لوسيا"] },
  { code: "vc", answers: ["سانت فينسنت والغرينادين"] },
  { code: "tt", answers: ["ترينيداد وتوباغو"] },
  { code: "us", answers: ["أمريكا", "الولايات المتحدة"] },

  // --- South America (12) ---
  { code: "ar", answers: ["الأرجنتين"] },
  { code: "bo", answers: ["بوليفيا"] },
  { code: "br", answers: ["البرازيل"] },
  { code: "cl", answers: ["تشيلي"] },
  { code: "co", answers: ["كولومبيا"] },
  { code: "ec", answers: ["الإكوادور"] },
  { code: "gy", answers: ["غيانا"] },
  { code: "py", answers: ["باراغواي"] },
  { code: "pe", answers: ["بيرو"] },
  { code: "sr", answers: ["سورينام"] },
  { code: "uy", answers: ["أوروغواي"] },
  { code: "ve", answers: ["فنزويلا"] },

  // --- Oceania (14) ---
  { code: "au", answers: ["أستراليا"] },
  { code: "fj", answers: ["فيجي"] },
  { code: "ki", answers: ["كيريباتي"] },
  { code: "mh", answers: ["جزر مارشال"] },
  { code: "fm", answers: ["ميكرونيزيا"] },
  { code: "nr", answers: ["ناورو"] },
  { code: "nz", answers: ["نيوزيلندا"] },
  { code: "pw", answers: ["بالاو"] },
  { code: "pg", answers: ["بابوا غينيا الجديدة"] },
  { code: "ws", answers: ["ساموا"] },
  { code: "sb", answers: ["جزر سليمان"] },
  { code: "to", answers: ["تونغا"] },
  { code: "tv", answers: ["توفالو"] },
  { code: "vu", answers: ["فانواتو"] },
];
