export interface LogoQuestion {
  /** `simple-icons` slug — matches the downloaded/colored SVG at `public/logos/<slug>.svg` on
   *  both frontends (see the copy step in the game's setup notes). */
  slug: string;
  answers: string[];
}

/**
 * The built-in logos bank — every entry is a real, currently-published `simple-icons` slug
 * (MIT-licensed, https://simpleicons.org), the standard open-source substitute for bundling
 * official trademarked artwork: actual company logo files are copyrighted/trademarked and can't
 * legally be scraped and redistributed by this app, so — exactly like Flags reuses `flag-icons`
 * instead of shipping real government flag files — Logos reuses Simple Icons' simplified,
 * single-color brand glyphs (recolored to each brand's own hex at copy time, see the asset step)
 * instead of shipping real logo files. That library only covers brands willing to be listed
 * there, so some very famous names (Amazon, Disney, Nintendo, most luxury fashion houses, most
 * MENA-local chains) simply aren't available anywhere it'd be legal to bundle them — this bank
 * is the largest genuinely-recognizable set obtainable from it, organized by category below
 * purely for editing sanity. `answers[0]` is also what `LogosState.brandName` reveals; several
 * acronym-heavy brands accept both the Arabic transliteration and the bare Latin acronym since
 * that's realistically how a fast-moving live chat types them.
 */
export const LOGOS_QUESTIONS: LogoQuestion[] = [
  // --- Tech giants / electronics (36) ---
  { slug: "google", answers: ["جوجل"] },
  { slug: "apple", answers: ["أبل", "آبل"] },
  { slug: "meta", answers: ["ميتا"] },
  { slug: "intel", answers: ["إنتل"] },
  { slug: "amd", answers: ["إيه إم دي", "amd"] },
  { slug: "nvidia", answers: ["إنفيديا", "نفيديا"] },
  { slug: "qualcomm", answers: ["كوالكوم"] },
  { slug: "cisco", answers: ["سيسكو"] },
  { slug: "dell", answers: ["ديل"] },
  { slug: "hp", answers: ["إتش بي", "hp"] },
  { slug: "lenovo", answers: ["لينوفو"] },
  { slug: "asus", answers: ["أسوس"] },
  { slug: "acer", answers: ["إيسر"] },
  { slug: "msi", answers: ["إم إس آي", "msi"] },
  { slug: "razer", answers: ["ريزر"] },
  { slug: "corsair", answers: ["كورسير"] },
  { slug: "xiaomi", answers: ["شاومي"] },
  { slug: "huawei", answers: ["هواوي"] },
  { slug: "oppo", answers: ["أوبو"] },
  { slug: "vivo", answers: ["فيفو"] },
  { slug: "motorola", answers: ["موتورولا"] },
  { slug: "nokia", answers: ["نوكيا"] },
  { slug: "blackberry", answers: ["بلاك بيري"] },
  { slug: "samsung", answers: ["سامسونج", "سامسونغ"] },
  { slug: "sony", answers: ["سوني"] },
  { slug: "lg", answers: ["إل جي", "lg"] },
  { slug: "panasonic", answers: ["باناسونيك"] },
  { slug: "bosch", answers: ["بوش"] },
  { slug: "siemens", answers: ["سيمنس"] },
  { slug: "nikon", answers: ["نيكون"] },
  { slug: "fujifilm", answers: ["فوجي فيلم", "فوجيفيلم"] },
  { slug: "kodak", answers: ["كوداك"] },
  { slug: "epson", answers: ["إبسون"] },
  { slug: "garmin", answers: ["جارمن"] },
  { slug: "fitbit", answers: ["فيت بيت", "فيتبيت"] },
  { slug: "dji", answers: ["دي جي آي", "dji"] },

  // --- Social / messaging / streaming (42) ---
  { slug: "facebook", answers: ["فيسبوك"] },
  { slug: "instagram", answers: ["إنستغرام", "انستقرام"] },
  { slug: "whatsapp", answers: ["واتساب", "واتسآب"] },
  { slug: "tiktok", answers: ["تيك توك"] },
  { slug: "snapchat", answers: ["سناب شات", "سناب"] },
  { slug: "youtube", answers: ["يوتيوب"] },
  { slug: "x", answers: ["تويتر", "إكس"] },
  { slug: "pinterest", answers: ["بينتريست"] },
  { slug: "reddit", answers: ["ريديت"] },
  { slug: "telegram", answers: ["تيليجرام", "تليجرام"] },
  { slug: "discord", answers: ["ديسكورد"] },
  { slug: "signal", answers: ["سيجنال"] },
  { slug: "viber", answers: ["فايبر"] },
  { slug: "wechat", answers: ["وي تشات"] },
  { slug: "line", answers: ["لاين"] },
  { slug: "zoom", answers: ["زووم"] },
  { slug: "tumblr", answers: ["تمبلر"] },
  { slug: "twitch", answers: ["تويتش"] },
  { slug: "spotify", answers: ["سبوتيفاي"] },
  { slug: "soundcloud", answers: ["ساوند كلاود"] },
  { slug: "shazam", answers: ["شازام"] },
  { slug: "netflix", answers: ["نتفليكس"] },
  { slug: "hbomax", answers: ["إتش بي أو ماكس", "hbo max"] },
  { slug: "paramountplus", answers: ["بارامونت بلس"] },
  { slug: "crunchyroll", answers: ["كرنشي رول"] },
  { slug: "deezer", answers: ["ديزر"] },
  { slug: "applemusic", answers: ["أبل ميوزيك"] },
  { slug: "pandora", answers: ["باندورا"] },
  { slug: "audible", answers: ["أوديبل"] },
  { slug: "myspace", answers: ["ماي سبيس"] },
  { slug: "flipboard", answers: ["فليب بورد"] },
  { slug: "vimeo", answers: ["فيميو"] },
  { slug: "dailymotion", answers: ["ديلي موشن"] },
  { slug: "bilibili", answers: ["بيلي بيلي"] },
  { slug: "niconico", answers: ["نيكو نيكو"] },
  { slug: "qq", answers: ["كيو كيو", "qq"] },
  { slug: "kakaotalk", answers: ["كاكاو توك"] },
  { slug: "kakao", answers: ["كاكاو"] },
  { slug: "naver", answers: ["نيفر"] },
  { slug: "zalo", answers: ["زالو"] },
  { slug: "threads", answers: ["ثريدز"] },
  { slug: "bluesky", answers: ["بلوسكاي"] },
  { slug: "mastodon", answers: ["ماستودون"] },

  // --- Gaming (21) ---
  { slug: "playstation", answers: ["بلايستيشن"] },
  { slug: "steam", answers: ["ستيم"] },
  { slug: "epicgames", answers: ["إيبك جيمز"] },
  { slug: "ea", answers: ["إي إيه", "ea"] },
  { slug: "activision", answers: ["أكتيفيجن"] },
  { slug: "ubisoft", answers: ["يوبيسوفت"] },
  { slug: "riotgames", answers: ["رايوت جيمز"] },
  { slug: "valve", answers: ["فالف"] },
  { slug: "roblox", answers: ["روبلوكس"] },
  { slug: "fortnite", answers: ["فورتنايت"] },
  { slug: "pubg", answers: ["ببجي"] },
  { slug: "leagueoflegends", answers: ["ليج أوف ليجندز", "ليج"] },
  { slug: "valorant", answers: ["فالورانت"] },
  { slug: "counterstrike", answers: ["كاونتر سترايك"] },
  { slug: "dota2", answers: ["دوتا"] },
  { slug: "supercell", answers: ["سوبر سيل"] },
  { slug: "rockstargames", answers: ["روكستار جيمز", "روكستار"] },
  { slug: "2k", answers: ["تو كيه", "2k"] },
  { slug: "sega", answers: ["سيجا"] },
  { slug: "squareenix", answers: ["سكوير إنكس"] },
  { slug: "konami", answers: ["كونامي"] },

  // --- Automotive (37) ---
  { slug: "bmw", answers: ["بي إم دبليو", "bmw"] },
  { slug: "audi", answers: ["أودي"] },
  { slug: "volkswagen", answers: ["فولكس فاجن", "فولكسفاجن"] },
  { slug: "toyota", answers: ["تويوتا"] },
  { slug: "honda", answers: ["هوندا"] },
  { slug: "nissan", answers: ["نيسان"] },
  { slug: "ford", answers: ["فورد"] },
  { slug: "chevrolet", answers: ["شيفروليه"] },
  { slug: "cadillac", answers: ["كاديلاك"] },
  { slug: "tesla", answers: ["تسلا"] },
  { slug: "ferrari", answers: ["فيراري"] },
  { slug: "lamborghini", answers: ["لامبورجيني"] },
  { slug: "porsche", answers: ["بورش"] },
  { slug: "bentley", answers: ["بنتلي"] },
  { slug: "rollsroyce", answers: ["رولز رويس"] },
  { slug: "astonmartin", answers: ["أستون مارتن"] },
  { slug: "bugatti", answers: ["بوجاتي"] },
  { slug: "maserati", answers: ["مازيراتي"] },
  { slug: "mini", answers: ["ميني"] },
  { slug: "fiat", answers: ["فيات"] },
  { slug: "peugeot", answers: ["بيجو"] },
  { slug: "renault", answers: ["رينو"] },
  { slug: "citroen", answers: ["سيتروين"] },
  { slug: "skoda", answers: ["سكودا"] },
  { slug: "seat", answers: ["سيات"] },
  { slug: "volvo", answers: ["فولفو"] },
  { slug: "hyundai", answers: ["هيونداي"] },
  { slug: "kia", answers: ["كيا"] },
  { slug: "mazda", answers: ["مازدا"] },
  { slug: "mitsubishi", answers: ["ميتسوبيشي"] },
  { slug: "suzuki", answers: ["سوزوكي"] },
  { slug: "subaru", answers: ["سوبارو"] },
  { slug: "jeep", answers: ["جيب"] },
  { slug: "ram", answers: ["رام"] },
  { slug: "chrysler", answers: ["كرايسلر"] },
  { slug: "acura", answers: ["أكيورا"] },
  { slug: "infiniti", answers: ["إنفينيتي"] },

  // --- Fashion / sportswear (11) ---
  { slug: "nike", answers: ["نايك"] },
  { slug: "adidas", answers: ["أديداس"] },
  { slug: "puma", answers: ["بوما"] },
  { slug: "reebok", answers: ["ريبوك"] },
  { slug: "underarmour", answers: ["أندر آرمور"] },
  { slug: "newbalance", answers: ["نيو بالانس"] },
  { slug: "fila", answers: ["فيلا"] },
  { slug: "zara", answers: ["زارا"] },
  { slug: "uniqlo", answers: ["يونيكلو"] },
  { slug: "dior", answers: ["ديور"] },
  { slug: "hermes", answers: ["هيرميس"] },

  // --- Food / beverage (8) ---
  { slug: "cocacola", answers: ["كوكاكولا", "كوكا كولا"] },
  { slug: "redbull", answers: ["ريد بول"] },
  { slug: "monster", answers: ["مونستر"] },
  { slug: "starbucks", answers: ["ستاربكس"] },
  { slug: "mcdonalds", answers: ["ماكدونالدز"] },
  { slug: "kfc", answers: ["كنتاكي", "kfc"] },
  { slug: "burgerking", answers: ["برجر كنج"] },
  { slug: "tacobell", answers: ["تاكو بيل"] },

  // --- Airlines (22) ---
  { slug: "emirates", answers: ["الإمارات", "طيران الإمارات"] },
  { slug: "qatarairways", answers: ["القطرية", "الخطوط القطرية"] },
  { slug: "saudia", answers: ["السعودية", "الخطوط السعودية"] },
  { slug: "turkishairlines", answers: ["الخطوط التركية", "التركية"] },
  { slug: "lufthansa", answers: ["لوفتهانزا"] },
  { slug: "airfrance", answers: ["إير فرانس"] },
  { slug: "britishairways", answers: ["الخطوط البريطانية", "بريتش إيرويز"] },
  { slug: "klm", answers: ["كيه إل إم", "klm"] },
  { slug: "ryanair", answers: ["راين إير"] },
  { slug: "easyjet", answers: ["إيزي جيت"] },
  { slug: "delta", answers: ["دلتا"] },
  { slug: "americanairlines", answers: ["أمريكان إيرلاينز"] },
  { slug: "airasia", answers: ["إير آسيا"] },
  { slug: "wizzair", answers: ["ويز إير"] },
  { slug: "jetblue", answers: ["جيت بلو"] },
  { slug: "qantas", answers: ["كوانتاس"] },
  { slug: "singaporeairlines", answers: ["الخطوط السنغافورية"] },
  { slug: "japanairlines", answers: ["الخطوط اليابانية"] },
  { slug: "ana", answers: ["إيه إن إيه", "ana"] },
  { slug: "indigo", answers: ["إنديجو"] },
  { slug: "norwegian", answers: ["نورويجيان"] },
  { slug: "aeroflot", answers: ["إيروفلوت"] },

  // --- Travel / ride-hailing / delivery (15) ---
  { slug: "airbnb", answers: ["إير بي إن بي", "airbnb"] },
  { slug: "tripadvisor", answers: ["تريب أدفايزر"] },
  { slug: "expedia", answers: ["إكسبيديا"] },
  { slug: "uber", answers: ["أوبر"] },
  { slug: "lyft", answers: ["ليفت"] },
  { slug: "grab", answers: ["جراب"] },
  { slug: "doordash", answers: ["دور داش"] },
  { slug: "ubereats", answers: ["أوبر إيتس"] },
  { slug: "deliveroo", answers: ["ديليفرو"] },
  { slug: "instacart", answers: ["إنستاكارت"] },
  { slug: "postmates", answers: ["بوست ميتس"] },
  { slug: "zomato", answers: ["زوماتو"] },
  { slug: "swiggy", answers: ["سويجي"] },
  { slug: "glovo", answers: ["جلوفو"] },
  { slug: "foodpanda", answers: ["فود باندا"] },

  // --- Payment / fintech (18) ---
  { slug: "visa", answers: ["فيزا"] },
  { slug: "mastercard", answers: ["ماستركارد"] },
  { slug: "paypal", answers: ["باي بال"] },
  { slug: "applepay", answers: ["أبل باي"] },
  { slug: "googlepay", answers: ["جوجل باي"] },
  { slug: "samsungpay", answers: ["سامسونج باي"] },
  { slug: "stripe", answers: ["سترايب"] },
  { slug: "square", answers: ["سكوير"] },
  { slug: "klarna", answers: ["كلارنا"] },
  { slug: "revolut", answers: ["ريفولوت"] },
  { slug: "wise", answers: ["وايز"] },
  { slug: "venmo", answers: ["فينمو"] },
  { slug: "cashapp", answers: ["كاش آب"] },
  { slug: "alipay", answers: ["علي باي"] },
  { slug: "americanexpress", answers: ["أمريكان إكسبريس"] },
  { slug: "payoneer", answers: ["بايونير"] },
  { slug: "westernunion", answers: ["ويسترن يونيون"] },
  { slug: "moneygram", answers: ["موني جرام"] },

  // --- Banking (5) ---
  { slug: "hsbc", answers: ["إتش إس بي سي", "hsbc"] },
  { slug: "chase", answers: ["تشيس"] },
  { slug: "bankofamerica", answers: ["بنك أوف أمريكا"] },
  { slug: "wellsfargo", answers: ["ويلز فارجو"] },
  { slug: "barclays", answers: ["باركليز"] },

  // --- Retail / e-commerce (9) ---
  { slug: "ebay", answers: ["إيباي", "ebay"] },
  { slug: "etsy", answers: ["إتسي"] },
  { slug: "aliexpress", answers: ["علي إكسبريس"] },
  { slug: "wish", answers: ["ويش"] },
  { slug: "target", answers: ["تارجت"] },
  { slug: "ikea", answers: ["إيكيا"] },
  { slug: "carrefour", answers: ["كارفور"] },
  { slug: "lidl", answers: ["ليدل"] },
  { slug: "tesco", answers: ["تيسكو"] },

  // --- Telecom (7) ---
  { slug: "vodafone", answers: ["فودافون"] },
  { slug: "orange", answers: ["أورانج"] },
  { slug: "verizon", answers: ["فيرايزون"] },
  { slug: "airtel", answers: ["إيرتل"] },
  { slug: "jio", answers: ["جيو"] },
  { slug: "bt", answers: ["بي تي", "bt"] },
  { slug: "deutschetelekom", answers: ["دويتشه تيليكوم"] },

  // --- Crypto (16) ---
  { slug: "bitcoin", answers: ["بيتكوين"] },
  { slug: "ethereum", answers: ["إيثيريوم"] },
  { slug: "binance", answers: ["بينانس"] },
  { slug: "coinbase", answers: ["كوين بيس"] },
  { slug: "tether", answers: ["تيثر"] },
  { slug: "dogecoin", answers: ["دوجكوين"] },
  { slug: "litecoin", answers: ["لايتكوين"] },
  { slug: "cardano", answers: ["كاردانو"] },
  { slug: "solana", answers: ["سولانا"] },
  { slug: "polkadot", answers: ["بولكادوت"] },
  { slug: "chainlink", answers: ["تشين لينك"] },
  { slug: "ripple", answers: ["ريبل"] },
  { slug: "bnbchain", answers: ["بي إن بي تشين", "bnb"] },
  { slug: "okx", answers: ["أو كيه إكس", "okx"] },
  { slug: "kucoin", answers: ["كوكوين"] },
  { slug: "opensea", answers: ["أوبن سي"] },

  // --- Browsers / operating systems (13) ---
  { slug: "googlechrome", answers: ["جوجل كروم", "كروم"] },
  { slug: "firefox", answers: ["فايرفوكس"] },
  { slug: "safari", answers: ["سفاري"] },
  { slug: "opera", answers: ["أوبرا"] },
  { slug: "brave", answers: ["بريف"] },
  { slug: "macos", answers: ["ماك أو إس", "macos"] },
  { slug: "linux", answers: ["لينكس"] },
  { slug: "ubuntu", answers: ["أوبونتو"] },
  { slug: "android", answers: ["أندرويد"] },
  { slug: "ios", answers: ["آي أو إس", "ios"] },
  { slug: "harmonyos", answers: ["هارموني أو إس"] },
  { slug: "duckduckgo", answers: ["داك داك جو"] },
  { slug: "baidu", answers: ["بايدو"] },

  // --- Google services / productivity (18) ---
  { slug: "gmail", answers: ["جيميل"] },
  { slug: "googlemaps", answers: ["جوجل مابس", "خرائط جوجل"] },
  { slug: "googledrive", answers: ["جوجل درايف"] },
  { slug: "googlephotos", answers: ["جوجل فوتوز"] },
  { slug: "googlecalendar", answers: ["جوجل كالندر"] },
  { slug: "googleplay", answers: ["جوجل بلاي"] },
  { slug: "appstore", answers: ["آب ستور", "app store"] },
  { slug: "googleearth", answers: ["جوجل إيرث"] },
  { slug: "waze", answers: ["ويز"] },
  { slug: "protonmail", answers: ["بروتون ميل"] },
  { slug: "zoho", answers: ["زوهو"] },
  { slug: "notion", answers: ["نوشن"] },
  { slug: "evernote", answers: ["إيفرنوت"] },
  { slug: "trello", answers: ["تريلو"] },
  { slug: "asana", answers: ["أسانا"] },
  { slug: "clickup", answers: ["كليك أب"] },
  { slug: "airtable", answers: ["إير تيبل"] },
  { slug: "figma", answers: ["فيجما"] },

  // --- Creative / freelance / crowdfunding (14) ---
  { slug: "patreon", answers: ["باتريون"] },
  { slug: "kickstarter", answers: ["كيك ستارتر"] },
  { slug: "gofundme", answers: ["جو فند مي"] },
  { slug: "fiverr", answers: ["فايفر"] },
  { slug: "upwork", answers: ["أب ورك"] },
  { slug: "freelancer", answers: ["فريلانسر"] },
  { slug: "behance", answers: ["بيهانس"] },
  { slug: "dribbble", answers: ["دريبل"] },
  { slug: "500px", answers: ["فايف هاندرد بيكس", "500px"] },
  { slug: "flickr", answers: ["فليكر"] },
  { slug: "unsplash", answers: ["أنسبلاش"] },
  { slug: "pexels", answers: ["بيكسلز"] },
  { slug: "pixabay", answers: ["بيكسا باي"] },
  { slug: "giphy", answers: ["جيفي"] },

  // --- Education (8) ---
  { slug: "duolingo", answers: ["دولينجو"] },
  { slug: "coursera", answers: ["كورسيرا"] },
  { slug: "udemy", answers: ["يوديمي"] },
  { slug: "khanacademy", answers: ["أكاديمية خان", "خان أكاديمي"] },
  { slug: "edx", answers: ["إيه دي إكس", "edx"] },
  { slug: "skillshare", answers: ["سكيل شير"] },
  { slug: "pluralsight", answers: ["بلورال سايت"] },
  { slug: "quizlet", answers: ["كويزلت"] },

  // --- News / media / entertainment (12) ---
  { slug: "cnn", answers: ["سي إن إن", "cnn"] },
  { slug: "theguardian", answers: ["الجارديان"] },
  { slug: "wikipedia", answers: ["ويكيبيديا"] },
  { slug: "imdb", answers: ["آي إم دي بي", "imdb"] },
  { slug: "rottentomatoes", answers: ["روتن توميتوز"] },
  { slug: "letterboxd", answers: ["ليتر بوكسد"] },
  { slug: "goodreads", answers: ["جود ريدز"] },
  { slug: "medium", answers: ["ميديم"] },
  { slug: "wordpress", answers: ["ووردبريس"] },
  { slug: "blogger", answers: ["بلوجر"] },
  { slug: "ghost", answers: ["غوست"] },
  { slug: "substack", answers: ["سبستاك"] },

  // --- Dating (2) ---
  { slug: "tinder", answers: ["تندر"] },
  { slug: "okcupid", answers: ["أوكيه كيوبيد"] },

  // --- Sports (5) ---
  { slug: "fifa", answers: ["فيفا"] },
  { slug: "nba", answers: ["إن بي إيه", "nba"] },
  { slug: "nhl", answers: ["إن إتش إل", "nhl"] },
  { slug: "mlb", answers: ["إم إل بي", "mlb"] },
  { slug: "premierleague", answers: ["الدوري الإنجليزي", "البريميرليج"] },

  // --- VPN / security (6) ---
  { slug: "nordvpn", answers: ["نورد في بي إن", "nordvpn"] },
  { slug: "expressvpn", answers: ["إكسبريس في بي إن", "expressvpn"] },
  { slug: "protonvpn", answers: ["بروتون في بي إن"] },
  { slug: "surfshark", answers: ["سيرف شارك"] },
  { slug: "openvpn", answers: ["أوبن في بي إن"] },
  { slug: "wireguard", answers: ["واير جارد"] },

  // --- Hosting / dev infra (mainstream-recognizable only) (4) ---
  { slug: "godaddy", answers: ["جو دادي"] },
  { slug: "cloudflare", answers: ["كلاود فلير"] },
  { slug: "github", answers: ["جيت هاب"] },
  { slug: "docker", answers: ["دوكر"] },
];
